name: CI - Executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  EXECUTABLES: "project"

jobs:
  docker-changes:
    runs-on: ubuntu-latest
    outputs:
      dockerfile: ${{ steps.filter.outputs.dockerfile }}

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            dockerfile:
              - '.github/docker/ci.Dockerfile'

  build-image:
    needs: docker-changes
    if: needs.docker-changes.outputs.dockerfile == 'true'

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}
      - run: |
          REPOSITORY_OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPOSITORY_OWNER_LOWERCASE/ci:latest -f .github/docker/ci.Dockerfile .github/docker/
          docker push ghcr.io/$REPOSITORY_OWNER_LOWERCASE/ci:latest

  build-executables:
    needs: [docker-changes, build-image]
    if: |
      always() &&
      needs.docker-changes.result == 'success' &&
      (needs.build-image.result == 'success' || needs.build-image.result == 'skipped')

    #runs-on: self-hosted
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/tsukini22/ci:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build executables
        run: |
          set -e
          make re
        timeout-minutes: 2

      - name: Check executables
        run: |
          set -euo pipefail
          for executable in $(echo $EXECUTABLES | tr ',' ' ' | xargs); do
            if [ ! -f "./$executable" ]; then
              echo "::error title=Missing executable, file=$executable::Executable '$executable' not found"
              exit 1
            fi
            if [ ! -x "$executable" ]; then
              echo "::error title=Permission error,file=$executable::Executable '$executable' has no execution permission"
              exit 1
            fi
            echo "✓ Executable '$executable' ok"
          done
