name: CI - Executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  EXECUTABLES: "project"

jobs:
  build-executables:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/tsukini22/ci:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: /github/home/.cache/ccache
          key: ccache-${{ runner.os }}-${{ hashFiles('**/*.cpp', '**/*.hpp', 'CMakeLists.txt') }}
          restore-keys: |
            ccache-${{ runner.os }}-

      - name: Build executables
        run: |
          set -e
          make re
        timeout-minutes: 2

      - name: Show ccache stats
        run: ccache -s

      - name: Check executables
        run: |
          set -euo pipefail
          for executable in $(echo $EXECUTABLES | tr ',' ' ' | xargs); do
            if [ ! -f "./$executable" ]; then
              echo "::error title=Missing executable, file=$executable::Executable '$executable' not found"
              exit 1
            fi
            if [ ! -x "$executable" ]; then
              echo "::error title=Permission error,file=$executable::Executable '$executable' has no execution permission"
              exit 1
            fi
            echo "✓ Executable '$executable' ok"
          done
