name: Build executables

on:
  workflow_run:
    workflows: ["Build CI image"]
    types: [completed]
  push:
    branches: [main]
    paths-ignore:
      - '.github/docker/Dockerfile'
  pull_request:
    branches: [main]

env:
  EXECUTABLES: "project"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      dockerfile: ${{ steps.filter.outputs.dockerfile }}

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            dockerfile:
              - '.github/docker/Dockerfile'

  buil_executables:
    needs: changes
    if: needs.changes.outputs.dockerfile == 'false'

    #runs-on: self-hosted
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/tsukini22/ci:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Compile program
        run: |
          set -e
          make re
        timeout-minutes: 2

      - name: Check executables
        run: |
          set -euo pipefail

          for executable in $(echo $EXECUTABLES | tr ',' ' ' | xargs); do
            if [ ! -f "./$executable" ]; then
              echo "::error title=Missing executable, file=$executable::Executable '$executable' not found"
              exit 1
            fi

            if [ ! -x "$executable" ]; then
              echo "::error title=Permission error,file=$executable::Executable '$executable' has no execution permission"
              exit 1
            fi

            echo "✓ Executable '$executable' ok"
          done
