name: CI - Setup

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/**'

env:
  # Names for testing purpose only
  PROJECT_NAME: "testing"
  CORE_NAME: "Test"

jobs:
  build-executables:
    runs-on: ${{ vars.RUNNER }}
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/tsukini22/ci:latest

    steps:
      - name: Setup repository
        uses: actions/checkout@v5
        run: |
          set -e
          wget -qO- https://raw.githubusercontent.com/TsukiNi22/cpp_project_template/main/setup.sh | bash -s -- $PROJECT_NAME $CORE_NAME
        timeout-minutes: 2

      - name: Cache ccache
        uses: actions/cache@v5
        with:
          path: /github/home/.cache/ccache
          key: ccache-${{ runner.os }}-${{ hashFiles('**/*.cpp', '**/*.hpp', 'cmake/libs/*.a', 'CMakeLists.txt') }}
          restore-keys: |
            ccache-${{ runner.os }}-

      - name: Build executables
        run: |
          set -e
          make re
        timeout-minutes: 2

      - name: Show ccache stats
        run: ccache -s

      - name: Check executables
        run: |
          set -euo pipefail
          if [ ! -f "./$PROJECT_NAME" ]; then
            echo "::error title=Missing executable, file=$PROJECT_NAME::Executable '$PROJECT_NAME' not found"
            exit 1
          fi
          if [ ! -x "$PROJECT_NAME" ]; then
            echo "::error title=Permission error,file=$PROJECT_NAME::Executable '$PROJECT_NAME' has no execution permission"
            exit 1
          fi
          echo "✓ Executable '$PROJECT_NAME' ok"
